---
version: 1.1.15
slug: assist_satellite
name: Assist Satellite Fast Wake
description: Turn HA host into a voice assistant with a connected microphone and speaker
url: https://github.com/OHF-Voice/apps/blob/main/assist_satellite
hassio_api: false
arch:
  - amd64
  - aarch64
init: false
discovery:
  - esphome
map:
  - share:rw
options:
  name: ""
  port: 6053
  audio_input_device: ""
  audio_output_device: ""  
  wake_word: "okay_nabu"
  stop_word: "stop"
  refractory_seconds: 2.0
  enable_thinking_sound: false
  wakeup_sound: "/usr/src/sounds/wake_word_triggered.flac"
  processing_sound: "/usr/src/sounds/processing.wav"
  timer_sound: "/usr/src/sounds/timer_finished.flac"
  timer_max_ring_seconds: 900.0
  mic_volume: 1.0
  mic_noise_suppression: 0
  mic_auto_gain: 0
  peripheral_host: "0.0.0.0"
  peripheral_port: 6055
  peripheral_volume_step: 0.05
  disable_peripheral_api: false  
  debug_logging: false
  enable_colored_debug: false
  mute_sound: "/usr/src/sounds/mute_switch_on.flac"
  unmute_sound: "/usr/src/sounds/mute_switch_off.flac"
  preferences_file: "/share/assist_satellite/preferences.json"
  download_dir: "/share/assist_satellite/local"
schema:
  name: str?
  port: int
  audio_input_device: str?
  audio_output_device: str?  
  wake_word: str
  stop_word: str
  refractory_seconds: float
  enable_thinking_sound: bool
  wakeup_sound: str
  processing_sound: str
  timer_sound: str
  timer_max_ring_seconds: float
  mic_volume: float
  mic_noise_suppression: "int(0,4)"
  mic_auto_gain: "int(0,31)"
  peripheral_host: str
  peripheral_port: int
  peripheral_volume_step: "float(0,1)"
  disable_peripheral_api: bool
  debug_logging: bool
  enable_colored_debug: bool
  mute_sound: str
  unmute_sound: str
  preferences_file: str
  download_dir: str
audio: true
host_network: true
homeassistant: 2026.3.0
